version: "3.9"

services:
  mariadb:
    image: mariadb:10.7
    ports:
      - 3306:3306
    volumes:
      - ./.data/mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_PASSWORD: root
      MARIADB_DATABASE: fidget-ecomm
